### ISSUE TITLE
Fix annotated examples

### ISSUE THREAD

**Issue by zeleniy** [zeleniy/ideogram#10]
* https://zeleniy.github.io/ideogram/examples/annotations_basic.html
* https://zeleniy.github.io/ideogram/examples/annotations_overlaid.html
* https://zeleniy.github.io/ideogram/examples/annotations_tracks.html
* https://zeleniy.github.io/ideogram/examples/annotations_external_data.html

**Comment by zeleniy** [comment]
Next examples fixed:
* https://zeleniy.github.io/ideogram/examples/annotations_tracks.html
* https://zeleniy.github.io/ideogram/examples/annotations_external_data.html

**Comment by zeleniy** [comment]
Done.

**Comment by mrouard** [comment]
There is still an issue when clicking on chromosome for close up.

**Comment by zeleniy** [comment]
Yes, i will fix it at the framework of task #12
